# Generated by Django 3.2.5 on 2021-07-03 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=14)),
                ('servicioContratado', models.CharField(max_length=20)),
                ('tecnologiaServicio', models.CharField(max_length=4)),
                ('planContratado', models.CharField(max_length=30)),
                ('cantidadDecos', models.IntegerField()),
                ('costoInstalacion', models.IntegerField()),
                ('fechaInstalacion', models.DateField()),
                ('Comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webClaro.comuna')),
            ],
        ),
    ]
