# Generated by Django 3.2.5 on 2021-07-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webClaro', '0002_imagenperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenperfil',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
