# Generated by Django 3.2.5 on 2021-07-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webClaro', '0003_alter_imagenperfil_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenperfil',
            name='usuario',
            field=models.CharField(max_length=20),
        ),
    ]
