# Generated by Django 3.2.5 on 2021-07-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webClaro', '0009_cliente_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=13),
        ),
    ]
