# Generated by Django 3.2.5 on 2021-07-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webClaro', '0010_alter_cliente_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='CantidadDecodificadores',
            fields=[
                ('nombre', models.CharField(max_length=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoInstalacion',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlanContratado',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioContratado',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TecnologiaServicio',
            fields=[
                ('nombre', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
    ]
