# Generated by Django 3.2.5 on 2021-07-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webClaro', '0011_cantidaddecodificadores_estadoinstalacion_plancontratado_serviciocontratado_tecnologiaservicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunasMetropolitana',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ComunasSexta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
    ]
