# Generated by Django 3.2.5 on 2021-07-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webClaro', '0012_comunasmetropolitana_comunassexta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Comuna',
            field=models.CharField(max_length=40),
        ),
    ]
