# Generated by Django 3.2.5 on 2021-07-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webClaro', '0013_alter_cliente_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cantidadDecos',
            field=models.CharField(max_length=1),
        ),
    ]
